### ISSUE TITLE
Could you help me understand the "fix sign" process?

### ISSUE THREAD

**Issue by tomleung1996** [phcsoares/econci#15]
Hi,

Thank you for your effort to implement the ECI algorithm!

However, I do have a question that needs your help. After calculating the ECI for each country and the PCI for each product, why there is an additional step to "fix the sign"? I know the rankings may be reversed without this step, but I can't find it in the papers or books by the authors. Is it a typical procedure in linear algebra? 

In addition, according to Kemp-Benedict ([2014](https://mpra.ub.uni-muenchen.de/60705/)), ECI and the diversity of countries are orthogonal. Does it mean that ECI is independent of diversity and should have a close-to-zero correlation coefficient? In my experiment with your and the official code, ECI and the diversity show a significant positive correlation (~0.5, both Pearson's and Spearman's correlation). Do I misunderstand what orthogonal means?

Thank you!

**Comment by phcsoares** [comment]
Hello @tomleung1996,

The step to fix the sign is there because an eigenvector is not just one vector, but all [nonzero scalar multiples of that vector](https://mathworld.wolfram.com/Eigenvector.html#:~:text=A%20nonzero%20scalar%20multiple%20of,often%20normalized%20to%20unit%20length.&text=%2C%20so%20any%20eigenvectors%20that%20are,are%20returned%20as%20zero%20vectors.). Due to the numerical optimization methods used to calculate the vectors, the sign might flip. Particularly, numpy will return the vector with magnitude 1. Thus, we correct the sign by the correlation with diversity (ubiquity), as more diverse economies (less ubiquitous products) tend to be more complex.

Here is a [video by 3Blue1Brown](https://www.youtube.com/watch?v=PFDu9oVAE-g) I like about eigenvectors where you can get a better understanding of why the multiples of eigenvectors can be treated the same.
